add_newline = false

[character]
format = """
[>](bold green) """

[username]
style_user = "green bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
style = "green bold"
ssh_only = false
format = "[@$hostname]($style)"
disabled = false

[directory]
format = ":[$path]($style)[$read_only]($read_only_style) "
style = "bold #f57800"

[git_status]
disabled = true
